apiVersion: v1
kind: ConfigMap
metadata:
  name: smartpark-config
  namespace: smartpark
data:
  SPRING_DATA_MONGODB_URI: "mongodb://smartpark-mongodb:27017/smartpark_db"
  SPRING_DATA_MONGODB_DATABASE: "smartpark_db"
  SERVER_PORT: "8082"
  SPRING_PROFILES_ACTIVE: "prod"

ubuntu@k8s-master-heat:~/smartpark-k8s$ cat 02-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: smartpark-secrets
  namespace: smartpark
type: Opaque
stringData:
  JWT_SECRET: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
